/* opcua-large-c2: open62541-based simulator for Koerber MCC machines.
 *
 * Loads OPC UA core + DI + PackML + TMC v2 + one Koerber MCC vendor
 * nodeset (selected by the MCC_VARIANT env var) into the address space
 * via pre-compiled C source generated by open62541's nodeset_compiler.
 *
 * Native open62541 is fast enough to serve AIO commander's discovery
 * browse for all four Koerber MCC variants well under the hardcoded
 * ~5 minute budget, even the largest MCC11470 (~50K reachable nodes).
 */

#include <open62541/server.h>
#include <open62541/server_config_default.h>
#include <open62541/plugin/create_certificate.h>
#include <open62541/plugin/log_stdout.h>
#include <open62541/plugin/pki_default.h>
#include <signal.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

#include "ns_di.h"
#include "ns_packml.h"
#include "ns_tmc.h"
#include "ns_mcc11420.h"
#include "ns_mcc11450.h"
#include "ns_mcc11470.h"
#include "ns_mcc11490.h"

/* AIO commander discovers OPC UA assets by walking every Object node
 * whose TypeDefinition derives from a DI/PackML/TMC equipment type
 * (DeviceType, MotorType, AnalogInputType, ...). The Koerber MCC vendor
 * nodesets are *very* deeply typed: a single MCC machine exposes
 * dozens-to-hundreds of typed sub-objects. To keep the discovery
 * result at "one DiscoveredAsset per OPC UA server" (the desired UX
 * for this demo), we walk the address space after loading and rewrite
 * every typed Object below the top-level DeviceSet child to use plain
 * BaseObjectType. The address-space content is preserved (no nodes
 * deleted), only the TypeDefinition references on descendants are
 * collapsed so commander treats the whole tree as one asset. */

typedef struct {
    UA_Server *server;
    /* depth==0 means the node we are visiting is a top-level DeviceSet
     * child (the one device we WANT to be discovered). depth>=1 means
     * we are inside that device's tree and should demote. */
    int depth;
} DemoteCtx;

static UA_StatusCode demote_visit(UA_NodeId childId, UA_Boolean isInverse,
                                  UA_NodeId referenceTypeId, void *handle);

static void demote_object(UA_Server *server, UA_NodeId node) {
    /* Find current HasTypeDefinition target(s) and remove them, then
     * point at BaseObjectType. We use UA_Server_forEachChildNodeCall
     * which iterates HasTypeDefinition refs as well via the generic
     * reference iteration if we filter inside the callback; instead
     * do an explicit browse for HasTypeDefinition. */
    UA_BrowseDescription bd;
    UA_BrowseDescription_init(&bd);
    bd.nodeId = node;
    bd.browseDirection = UA_BROWSEDIRECTION_FORWARD;
    bd.includeSubtypes = false;
    bd.referenceTypeId = UA_NODEID_NUMERIC(0, UA_NS0ID_HASTYPEDEFINITION);
    bd.resultMask = UA_BROWSERESULTMASK_NONE;
    UA_BrowseResult br = UA_Server_browse(server, 0, &bd);
    UA_Boolean already_base = UA_FALSE;
    for (size_t i = 0; i < br.referencesSize; i++) {
        UA_NodeId target = br.references[i].nodeId.nodeId;
        if (target.namespaceIndex == 0 &&
            target.identifierType == UA_NODEIDTYPE_NUMERIC &&
            target.identifier.numeric == UA_NS0ID_BASEOBJECTTYPE) {
            already_base = UA_TRUE;
            continue;
        }
        UA_ExpandedNodeId exp;
        UA_ExpandedNodeId_init(&exp);
        exp.nodeId = target;
        UA_Server_deleteReference(server, node,
            UA_NODEID_NUMERIC(0, UA_NS0ID_HASTYPEDEFINITION),
            UA_TRUE, exp, UA_TRUE);
    }
    UA_BrowseResult_clear(&br);
    if (!already_base) {
        UA_Server_addReference(server, node,
            UA_NODEID_NUMERIC(0, UA_NS0ID_HASTYPEDEFINITION),
            UA_EXPANDEDNODEID_NUMERIC(0, UA_NS0ID_BASEOBJECTTYPE),
            UA_TRUE);
    }
}

static UA_StatusCode demote_visit(UA_NodeId childId, UA_Boolean isInverse,
                                  UA_NodeId referenceTypeId, void *handle) {
    if (isInverse) return UA_STATUSCODE_GOOD;
    DemoteCtx *ctx = (DemoteCtx *)handle;
    /* Only follow into namespaces >=1 (skip ns=0 standard nodes). */
    if (childId.namespaceIndex == 0) return UA_STATUSCODE_GOOD;
    /* Hard depth cap to avoid runaway recursion / cycles. */
    if (ctx->depth > 12) return UA_STATUSCODE_GOOD;
    /* Only follow HasComponent / Organizes; ignore HasProperty etc.
     * to keep the work bounded. */
    if (!(referenceTypeId.namespaceIndex == 0 &&
          referenceTypeId.identifierType == UA_NODEIDTYPE_NUMERIC &&
          (referenceTypeId.identifier.numeric == UA_NS0ID_HASCOMPONENT ||
           referenceTypeId.identifier.numeric == UA_NS0ID_ORGANIZES))) {
        return UA_STATUSCODE_GOOD;
    }

    UA_NodeClass nc = UA_NODECLASS_UNSPECIFIED;
    if (UA_Server_readNodeClass(ctx->server, childId, &nc)
            != UA_STATUSCODE_GOOD) {
        return UA_STATUSCODE_GOOD;
    }
    if (nc == UA_NODECLASS_OBJECT && ctx->depth >= 1) {
        demote_object(ctx->server, childId);
    }
    if (nc == UA_NODECLASS_OBJECT) {
        DemoteCtx child_ctx = { ctx->server, ctx->depth + 1 };
        UA_Server_forEachChildNodeCall(ctx->server, childId,
                                       demote_visit, &child_ctx);
    }
    return UA_STATUSCODE_GOOD;
}

static void flatten_devicesets(UA_Server *server, const char *variant) {
    size_t di_ns = 0;
    UA_String di_uri = UA_STRING("http://opcfoundation.org/UA/DI/");
    if (UA_Server_getNamespaceByName(server, di_uri, &di_ns)
            != UA_STATUSCODE_GOOD) {
        fprintf(stderr, "[%s] DI namespace not found, skipping flatten\n",
                variant);
        return;
    }
    fprintf(stderr, "[%s] flatten_devicesets: starting (DI ns=%zu)\n",
            variant, di_ns);
    fflush(stderr);
    UA_NodeId deviceset = UA_NODEID_NUMERIC((UA_UInt16)di_ns, 5001);
    /* Keep every direct child of DeviceSet typed as its DI Device type
     * (these are surfaced as DiscoveredAssets by AIO commander - one
     * per logical "Device" in the OPC UA DI sense). Demote everything
     * BELOW each top-level Device to BaseObjectType so motors / valves
     * / sensors / etc. don't pollute discovery as separate assets. */
    DemoteCtx ctx = { server, 0 };
    UA_StatusCode sc = UA_Server_forEachChildNodeCall(server, deviceset,
                                                      demote_visit, &ctx);
    fprintf(stderr, "[%s] flatten_devicesets: done %s\n", variant,
            UA_StatusCode_name(sc));
    fflush(stderr);
}

static volatile UA_Boolean running = true;
static void stopHandler(int sig) {
    (void)sig;
    running = false;
}

int main(void) {
    signal(SIGINT, stopHandler);
    signal(SIGTERM, stopHandler);

    const char *variant = getenv("MCC_VARIANT");
    if (!variant) variant = "MCC11490";

    int port = 4843;
    UA_StatusCode (*load_mcc)(UA_Server *) = NULL;
    if (strcmp(variant, "MCC11420") == 0) {
        port = 4840; load_mcc = ns_mcc11420;
    } else if (strcmp(variant, "MCC11450") == 0) {
        port = 4841; load_mcc = ns_mcc11450;
    } else if (strcmp(variant, "MCC11470") == 0) {
        port = 4842; load_mcc = ns_mcc11470;
    } else if (strcmp(variant, "MCC11490") == 0) {
        port = 4843; load_mcc = ns_mcc11490;
    } else {
        fprintf(stderr, "unknown MCC_VARIANT '%s'\n", variant);
        return 2;
    }

    char endpoint_path[64];
    snprintf(endpoint_path, sizeof(endpoint_path), "/aio-demo-%s",
             /* lowercase variant */
             ({
                 static char lc[16];
                 size_t i; for (i = 0; variant[i] && i < sizeof(lc) - 1; i++) {
                     char c = variant[i];
                     lc[i] = (c >= 'A' && c <= 'Z') ? (c + 32) : c;
                 }
                 lc[i] = '\0';
                 lc;
             }));

    fprintf(stderr, "[%s] starting opcua-large-c2 on port %d, endpoint %s\n",
            variant, port, endpoint_path);

    UA_Server *server = UA_Server_new();
    UA_ServerConfig *cfg = UA_Server_getConfig(server);

    /* Generate a self-signed certificate at startup so the server can
     * offer Basic256Sha256/Sign+SignAndEncrypt endpoints in addition to
     * None. The AIO commander selects the highest-security endpoint
     * the server advertises and refuses to connect if only None is
     * available. The cert is in-memory only; the broker accepts it via
     * its "autoAcceptUntrustedServerCertificates" setting. */
    UA_ByteString certificate = UA_BYTESTRING_NULL;
    UA_ByteString privateKey = UA_BYTESTRING_NULL;
    {
        char app_uri[64];
        snprintf(app_uri, sizeof(app_uri),
                 "URI:urn:aio-demo:c2:%s", variant);
        UA_String subject[3] = {
            UA_STRING_STATIC("C=CH"),
            UA_STRING_STATIC("O=AIODemo"),
            UA_STRING_STATIC("CN=AIO Demo MCC Simulator")
        };
        UA_String san[2] = {
            UA_STRING_STATIC("DNS:localhost"),
            UA_STRING(app_uri)
        };
        UA_KeyValueMap *kvm = UA_KeyValueMap_new();
        UA_UInt16 expiresIn = 365;
        UA_UInt16 keySize = 2048;
        UA_KeyValueMap_setScalar(kvm,
            UA_QUALIFIEDNAME(0, "expires-in-days"),
            (void*)&expiresIn, &UA_TYPES[UA_TYPES_UINT16]);
        UA_KeyValueMap_setScalar(kvm,
            UA_QUALIFIEDNAME(0, "key-size-bits"),
            (void*)&keySize, &UA_TYPES[UA_TYPES_UINT16]);
        UA_StatusCode csc = UA_CreateCertificate(
            UA_Log_Stdout, subject, 3, san, 2,
            UA_CERTIFICATEFORMAT_DER, kvm, &privateKey, &certificate);
        UA_KeyValueMap_delete(kvm);
        if (csc != UA_STATUSCODE_GOOD) {
            fprintf(stderr, "UA_CreateCertificate failed: %s\n",
                    UA_StatusCode_name(csc));
            return 3;
        }
    }

    UA_StatusCode sc = UA_ServerConfig_setDefaultWithSecurityPolicies(
        cfg, port, &certificate, &privateKey,
        NULL, 0, NULL, 0, NULL, 0);
    if (sc != UA_STATUSCODE_GOOD) {
        fprintf(stderr, "setDefaultWithSecurityPolicies failed: %s\n",
                UA_StatusCode_name(sc));
        return 4;
    }
    UA_ByteString_clear(&certificate);
    UA_ByteString_clear(&privateKey);

    /* Accept any client cert without a populated trust list. */
    cfg->secureChannelPKI.clear(&cfg->secureChannelPKI);
    cfg->sessionPKI.clear(&cfg->sessionPKI);
    UA_CertificateVerification_AcceptAll(&cfg->secureChannelPKI);
    UA_CertificateVerification_AcceptAll(&cfg->sessionPKI);


    /* Load nodesets in dependency order. ``BadInternalError`` /
     * ``BadTypeMismatch`` from a single node load are tolerated here:
     * the open62541 nodeset_compiler's generated initialiser stops at
     * the first non-good StatusCode, but in practice a small number of
     * Koerber nodes have type-mismatched default Variant values that
     * the generator emits but the runtime rejects. Logging and
     * continuing is acceptable for a discovery-focused simulator. */
    fprintf(stderr, "[%s] loading DI nodeset\n", variant);
    sc = ns_di(server);
    if (sc != UA_STATUSCODE_GOOD) {
        fprintf(stderr, "DI nodeset load returned %s (continuing)\n",
                UA_StatusCode_name(sc));
    }
    fprintf(stderr, "[%s] loading PackML nodeset\n", variant);
    sc = ns_packml(server);
    if (sc != UA_STATUSCODE_GOOD) {
        fprintf(stderr, "PackML nodeset load returned %s (continuing)\n",
                UA_StatusCode_name(sc));
    }
    fprintf(stderr, "[%s] loading TMC v2 nodeset\n", variant);
    sc = ns_tmc(server);
    if (sc != UA_STATUSCODE_GOOD) {
        fprintf(stderr, "TMC nodeset load returned %s (continuing)\n",
                UA_StatusCode_name(sc));
    }
    fprintf(stderr, "[%s] loading MCC vendor nodeset\n", variant);
    sc = load_mcc(server);
    if (sc != UA_STATUSCODE_GOOD) {
        fprintf(stderr, "MCC nodeset load returned %s (continuing)\n",
                UA_StatusCode_name(sc));
    }

    fprintf(stderr, "[%s] address space ready, server running\n", variant);
    fflush(stderr);

    /* Note: no address-space post-processing. The Koerber MCC nodesets
     * already model each motor / valve / sensor / equipment module as a
     * typed DI instance, which is what a real Koerber TMC server exposes
     * over OPC UA. AIO commander will surface every typed Object as its
     * own DiscoveredAsset (hundreds per machine). That is the realistic
     * "what you'd see at a real plant" view. */

    sc = UA_Server_run(server, &running);
    UA_Server_delete(server);
    return sc == UA_STATUSCODE_GOOD ? 0 : 1;
}
